### ISSUE TITLE
IMPORTANT - PLEASE UPDATE YOUR API ENDPOINT 

### ISSUE THREAD

**Issue by EduardoMartinezCatala** [singer-io/tap-fixerio#3]
IMPORTANT - PLEASE UPDATE YOUR API ENDPOINT 

https://github.com/fixerAPI/fixer#readme  

> CRITICAL Error on https://api.fixer.io/2018-06-18?base=USD; received status 404

**Comment by timvisher** [comment]
This has been fixed.
